### ISSUE TITLE
MacOS Ventura 13.4.1  导入 cBit_IR_V2 库后无法编译通过

### ISSUE THREAD

**Issue by mebusy** [zhuning239/cBit_IR_V2#1]
非常简单的测试程序

`basic.show_number(7)

def on_forever():
    pass
basic.forever(on_forever)`

初始工程，一切编译下载都正常。 但是一旦导入 cBit_IR_V2库后，无法编译下载，提示
"The hex file is not available, please connect to internet and try again."

**Comment by zhuning239** [comment]
您的邮件，我以收到，我会以最快的速度回复您！湖南科瑞特科技股份有限公司  技术部：朱林电话：13975851837

**Comment by zhuning239** [comment]
您的邮件，我以收到，我会以最快的速度回复您！湖南科瑞特科技股份有限公司  技术部：朱林电话：13975851837
